---
#
# config/webhook/admission_webhook.yaml
#
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "eg.fullname" . }}-admission
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "eg.labels" . | nindent 4 }}
webhooks:
  - name: validate.gateway.networking.k8s.io
    matchPolicy: Equivalent
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["gateway.networking.k8s.io"]
        apiVersions: ["v1alpha2", "v1beta1"]
        resources: ["gateways", "gatewayclasses", "httproutes"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "eg.fullname" . }}-admission-server
        namespace: '{{ .Release.Namespace }}'
        path: "/validate"
