name: cd
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+.*'
    branches:
    - teleport

permissions:
  contents: read

jobs: 

  push:
    name: Build and Push
    permissions:
      contents: read
      checks: read
      id-token: write
    env:
      AWS_REGION: us-east-1
      ECR_AWS_ROLE: arn:aws:iam::146628656107:role/envoy-gateway-github-action-ecr-role
    runs-on: ubuntu-latest
    needs: [verify, test]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.ECR_AWS_ROLE }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
      with:
        registry-type: public
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push gateway
      run: PLATFORM="linux_amd64" make teleport-push
    - name: Build and push helm
      run: make teleport-helm-push

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
    - name: Run Verify
      run: make teleport-verify

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
    - name: Unit Tests
      run: make teleport-test
