name: ci
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - labeled
    - unlabeled

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [verify, test]
    steps:
    - name: Install btrfs headers
      run: sudo apt-get install libbtrfs-dev -y
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build gateway
      run: PLATFORM="linux_amd64" make teleport-build
    - name: Build gateway helm
      run: CHART_VERSION=v0.0.0-latest TAG=latest make teleport-helm-package

  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
    - name: Run Verify
      run: make teleport-verify

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache: true
    - name: Unit Tests
      run: make teleport-test
